# Change these first
owner: fsdh-pfds # Your GitHub organization or username, where this repository lives
repo: status-statut # The name of this repository

sites:
  - name: Datahub Home
    url: https://sds.canada.ca
  - name: Production FSDH Portal
    url: https://federal-science-datahub.canada.ca/login

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: status-statut.sds.canada.ca 
  baseUrl: /status-statut
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status-Statut
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  customHeadHtml: |
    <!-- Icons Font Awesome (to access icons, import Font Awesome) -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" crossorigin="anonymous">
    <!-- GC Design System -->
    <link rel="stylesheet" href="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@0.32.0/dist/gcds/gcds.css">
    <script type="module" src="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@0.32.0/dist/gcds/gcds.esm.js"></script>
    <script nomodule src="https://cdn.design-system.alpha.canada.ca/@cdssnc/gcds-components@0.32.0/dist/gcds/gcds.js"></script>

  customBodyHtml: |
    <gcds-header lang=en lang-href=https://sds.canada.ca/fr/ signature-variant=colour skip-to-href=#> 
        <gcds-search lang=en slot=search action=/sr/srb.html placeholder=Canada.ca></gcds-search>
        <gcds-top-nav slot=menu label="Top navigation" alignment=right>
            <gcds-nav-link href=/ slot=home>Federal Science DataHub</gcds-nav-link>
            <gcds-nav-group open-trigger=Product menu-label=Product>
            <gcds-nav-link href=/product>Overview</gcds-nav-link>
            <gcds-nav-link href=/product/storage>Storage</gcds-nav-link>
            </gcds-nav-link>
        </gcds-nav-group>
        <gcds-nav-group open-trigger=Resources menu-label=Resources>
            <gcds-nav-link href=https://github.com/ssc-sp/datahub-portal/releases>Product updates</gcds-nav-link>
            <gcds-nav-link href=https://gcxgce.sharepoint.com/teams/10002160>GCxchange community</gcds-nav-link>
        </gcds-nav-group>
            <gcds-nav-link href=https://federal-science-datahub.canada.ca/ slot>Log in</gcds-nav-link>
        </gcds-top-nav>
        <gcds-breadcrumbs slot=breadcrumb>
            <gcds-breadcrumbs-item href=/>Federal Science DataHub</gcds-breadcrumbs-item>
        </gcds-breadcrumbs>
        <gcds-topic-menu slot=menu lang=en></gcds-topic-menu>
    </gcds-header>

