---
name: Configure CI
on:
  push:
    paths:
      - ".upptimerc.yml"
  repository_dispatch:
    types: [setup]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Configure Upptime
    runs-on: ubuntu-latest
    steps:
      - name: Create App token
        id: create_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.FSDH_UPPTIME_BOT_APP_ID }}
          private-key: ${{ secrets.FSDH_UPPTIME_BOT_APP_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.create_token.outputs.token }}
      - name: Update template
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "update-template"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}
      - name: Update response time
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "response-time"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
      - name: Update summary in README
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "readme"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}
      - name: Generate graphs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Graphs CI
          token: ${{ steps.create_token.outputs.token }}
      - name: Generate site
        uses: upptime/uptime-monitor@v1.39.0
        with:
          command: "site"
        env:
          GH_PAT: ${{ steps.create_token.outputs.token }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site/status-page/__sapper__/export/

      - name: Remove workflows files
        run: |
          FILES_TO_REMOVE=(".github/workflows/update-template.yml" ".github/workflows/site.yml" ".github/workflows/setup.yml")
          REMOVED=false
          for file in "${FILES_TO_REMOVE[@]}"; do
            if [ -f "$file" ]; then
              echo "File $file found. Removing..."
              git rm "$file"
              REMOVED=true
            else
              echo "File $file not found. Skipping removal."
            fi
          done
          if [ "$REMOVED" = true ]; then
            git config user.name "Upptime Bot"
            git config user.email "73812536+upptime-bot@users.noreply.github.com"
            git commit -m "Remove workflows files: ${FILES_TO_REMOVE[*]}"
            git push origin ${{ github.head_ref }}
          fi

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4